### PR TITLE
Permute Task1

### PR DESCRIPTION
**Pull request by Learnmore666**
According Permute task1,add Permute for relu,cast,sigmoid,addconst and onnx graph test,due to the use of helper tools to build onnx graph, onnx_ opt tool automatically removes the cast operator from graph. There are no test files related to cast operator here, and the mlir file containing the cast operator passed the tpuc-opt test separately.

### CODE REVIEW

**Comment by charlesxzb** [comment]
Hi, thanks for your contribution. However, have you passed the test_onnx.py yet? It failed from my side. I noticed that you didn't change the name of permuteOp, which results in the comparison problem (e.g., Top Mlir permuteOp after Relu vs ONNX permuteOp before Relu). 

Maybe you can add an additional op right after relu + permute in the test case so that it only compares the result of the last op. 

By the way, it would be great if you can merge your commits into one, it would be more convenient for us to review your overall solution.

**Comment by charlesxzb** [comment]
Normally top.castOp only occurs in the case of tflite (it is already int8 quantized in the top dialect). You can try to add the test case for cast+permute in test_tflite.py, which is similar to test_onnx.py.

**Comment by Learnmore666** [comment]
> 
That's okay.I also encountered testing issues with Cast operator. Based on my understanding, the onnx helper tool uses onnx_opt tool when building onnx model.The onnx_opt tool automatically removes the Cast operator from the model, while the tflite model also lacks the Cast operator after construction. Therefore, I cannot find the operator in the original mlir file and capture the pattern for testing.

**Comment by charlesxzb** [comment]
Hey, sorry for my late reply. It's been quite busy recently. Yeah, I just checked that and found this problem is unsolvable for now. So I think we will just stop here. Looking forward to your other contribution in the future.

**Pull request closed without merging**
